# Generated by Django 3.1.2 on 2021-01-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210111_1554'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_photos',
            field=models.ManyToManyField(blank=True, to='app.Photo'),
        ),
    ]
