# Generated by Django 3.1.2 on 2021-01-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210110_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='comment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='user',
            new_name='post_user',
        ),
    ]
