# Generated by Django 3.1.2 on 2021-01-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_photo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='address',
            new_name='place_name',
        ),
    ]
