# Generated by Django 3.1.2 on 2021-01-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210113_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
