# Generated by Django 3.1.2 on 2021-02-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=30),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lng',
            field=models.DecimalField(decimal_places=7, max_digits=30),
        ),
    ]
